openapi: 3.0.1
info:
  title: 'Pokemon Unite v1 - ApplicationError'
  version: v1
paths: {}
components:
  schemas:
    applicationError:
      type: object
      properties:
        code:
          type: string
          description: 'Error code.'
          example: ''
        message:
          type: string
          description: 'Error description.'
          example: ''
        developerMessage:
          type: string
          description: 'Detailed error description.'
          example: ''
        exception:
          type: object
          description: 'Thrown exception.'
          example: ''
        moreInformation:
          type: string
          description: 'Additional information.'
          example: ''
      description: 'Returned error.'
