openapi: 3.0.2
info:
  title: Pokemon Unite API v1 - Item Held
  version: v1
paths: {}
components:
  schemas:
    itemHeld:
      type: object
      properties:
        id:
          type: string
          description: Pokemon identifier.
          format: uuid
          readOnly: true
        name:
          type: string
          description: Pokemon name.
        cooldows:
          type: integer
          format: int32
          description: cooldown time in seconds
        digitalAssets:
          type: array
          items:
            type: string
            format: uri
        updatedDate:
          type: string
          description: The date when the pokemon was last updated (UTC).
          format: date-time
          readOnly: true
        createdDate:
          type: string
          description: The date when the pokemon was last updated (UTC).
          format: date-time
          readOnly: true