openapi: 3.0.2
info:
  title: Pokemon Unite API v1 - Item
  version: v1
paths: {}
components:
  schemas:
    item:
      type: object
      properties:
        id:
          type: string
          description: Pokemon identifier.
          format: uuid
          readOnly: true
        name:
          type: string
          description: Pokemon name.
        digitalAssets:
          type: array
          items:
            type: string
            format: uri
        updatedDate:
          type: string
          description: The date when the pokemon was last updated (UTC).
          format: date-time
          readOnly: true
        createdDate:
          type: string
          description: The date when the pokemon was last updated (UTC).
          format: date-time
          readOnly: true
        type:
          enum:
            - Consumable
            - Fashion