openapi: 3.0.2
info:
  title: Pokemon Unite API v1 - Pokemon API
  version: v1
paths:
  '/v1/pokemons/moves/{id}':
    get:
      tags:
        - PokemonMoves
      summary: Get a Pokemon move based on a identifier.
      operationId: PokemonMove_Get
      parameters:
        - name: id
          in: path
          description: Pokemon move identifier
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PokemonMove'
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/applicationErrorCollection'
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/applicationErrorCollection'
        "403":
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/applicationErrorCollection'
        '404':
          description: Not Found
        "500":
          description: Internar Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/applicationErrorCollection'
    post:
      tags:
        - PokemonMoves
      summary: Creates a Pokemon move.
      operationId: PokemonMove_Post
      requestBody:
        description: 'Pokemon move to save'
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PokemonMove'
        required: true
      responses:
        '201':
          description: Created
          headers:
            Location:
              description: '/pokemons/moves/{id}'
              schema:
                type: string
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/applicationErrorCollection'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/applicationErrorCollection'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/applicationErrorCollection'
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/applicationErrorCollection'
    put:
      tags:
        - Pokemon
      summary: Updates a Pokemon move
      operationId: PokemonMove_Put
      requestBody:
        description: 'Pokemon move to save'
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PokemonMove'
        required: true
      responses:
        '204':
          description: NoContent
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/applicationErrorCollection'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/applicationErrorCollection'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/applicationErrorCollection'
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/applicationErrorCollection'
  '/v1/pokemons/moves':
    get:
      tags:
       - PokemonMove
      summary: Get a page of pokemons moves based on parameters.
      operationId: PokemonMove_GetAll
      parameters:
        - name: page
          in: query
          description: Page Number. If it's null the default value is 1
          required: false
          schema:
            type: integer
            format: int32
        - name: pageSize
          in: query
          description: Page Size. If it's null the default value is 60
          required: false
          schema:
            type: integer
            format: int32
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Page_PokemonMoves'
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/applicationErrorCollection'
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/applicationErrorCollection'
        "403":
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/applicationErrorCollection'
        '404':
          description: Not Found
        "500":
          description: Internar Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/applicationErrorCollection'
    
components:
  schemas:
    PokemonMove:
      $ref: 'components/schemas/pokemon.move.yaml#/components/schemas/pokemonMove'
    Page_PokemonMoves:
      $ref: 'components/schemas/page_pokemonMoves.yaml#/components/schemas/pagePokemonMoves'
    applicationErrorCollection:
      $ref: '../shared-components/schemas/applicationErrorCollection.yaml#/components/schemas/applicationErrorCollection'
